In [ ]:
import pandas as pd

df_teste = pd.DataFrame({
    "nome": ["Jonas", "Ana", "Roberto", "Samuel", "Breno", "Alexandre"],
    "idade": [28, 15, 35, 29, 30, 49]
})

df_teste

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/Jonasjkb/analise-dados-mental-health/refs/heads/main/data/raw_mental_health.csv")

df.info()
df.describe()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 1705 entries, 0 to 1704
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Student_ID                    1705 non-null   int64
 1   Age                           1705 non-null   int64
 2   Gender                        1705 non-null   str
 3   Academic_Level                1705 non-null   str
 4   Country                       1705 non-null   str
 5   Avg_Daily_Usage_Hours         1705 non-null   float64
 6   Most_Used_Platform            1705 non-null   str
 7   Affects_Academic_Performance  1705 non-null   str
 8   Sleep_Hours_Per_Night         1705 non-null   float64
 9   Mental_Health_Score           1705 non-null   float64
 10  Overall_Impact                1705 non-null   str
dtypes: float64(3), int64(2), str(6)
memory usage: 212.3 KB

Student_ID                      0
Age                             0
Gender                          0
Academic_Level                  0
Country                         0
Avg_Daily_Usage_Hours           0
Most_Used_Platform              0
Affects_Academic_Performance    0
Sleep_Hours_Per_Night           0
Mental_Health_Score             0
Overall_Impact                  0
dtype: int64

In [5]:
df.head()

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Overall_Impact
0,232,21,Male,Undergraduate,Other,4.0,Facebook,No,6.7,6.8,Neutral
1,564,23,Female,Undergraduate,Other,1.6,LinkedIn,No,8.6,7.6,Positive
2,788,22,Male,Graduate,Canada,4.6,Instagram,No,6.7,7.0,Neutral
3,686,18,Male,Undergraduate,Other,7.0,Snapchat,Yes,5.4,5.3,Negative
4,608,24,Female,High School,Other,7.5,Facebook,Yes,5.0,4.4,Negative

In [6]:
df.describe(include=object)

C:\Users\Jonas\AppData\Local\Temp\ipykernel_16896\3998025828.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include=object)

,Gender,Academic_Level,Country,Most_Used_Platform,Affects_Academic_Performance,Overall_Impact
count,1705,1705,1705,1705,1705,1705
unique,2,3,111,12,2,3
top,Male,Undergraduate,Other,Instagram,Yes,Negative
freq,878,721,667,389,1011,939

In [8]:
df.shape

(1705, 11)

In [9]:
df.columns

Index(['Student_ID', 'Age', 'Gender', 'Academic_Level', 'Country',
       'Avg_Daily_Usage_Hours', 'Most_Used_Platform',
       'Affects_Academic_Performance', 'Sleep_Hours_Per_Night',
       'Mental_Health_Score', 'Overall_Impact'],
      dtype='str')

In [10]:
df = df.rename(columns={
    'Student_ID': 'ID_Aluno',
    'Age': 'Idade',
    'Gender': 'Gênero',
    'Academic_Level': 'Nível_Acadêmico',
    'Country': 'País',
    'Avg_Daily_Usage_Hours': 'Média_Horas_Uso_Diário',
    'Most_Used_Platform': 'Plataforma_Mais_Utilizada',
    'Affects_Academic_Performance': 'Afeta_Desempenho_Acadêmico',
    'Sleep_Hours_Per_Night': 'Horas_Sono_Por_Noite',
    'Mental_Health_Score': 'Pontuação_Saúde_Mental',
    'Overall_Impact': 'Impacto_Geral'
})

df.columns

Index(['ID_Aluno', 'Idade', 'Gênero', 'Nível_Acadêmico', 'País',
       'Média_Horas_Uso_Diário', 'Plataforma_Mais_Utilizada',
       'Afeta_Desempenho_Acadêmico', 'Horas_Sono_Por_Noite',
       'Pontuação_Saúde_Mental', 'Impacto_Geral'],
      dtype='str')

In [16]:
df.columns = (
    df.columns
      .str.strip()
      .str.upper()
      .str.replace(" ", "_")
)

df.columns

Index(['ID_ALUNO', 'IDADE', 'GÊNERO', 'NÍVEL_ACADÊMICO', 'PAÍS',
       'MÉDIA_HORAS_USO_DIÁRIO', 'PLATAFORMA_MAIS_UTILIZADA',
       'AFETA_DESEMPENHO_ACADÊMICO', 'HORAS_SONO_POR_NOITE',
       'PONTUAÇÃO_SAÚDE_MENTAL', 'IMPACTO_GERAL'],
      dtype='str')

In [18]:
df["GÊNERO"].value_counts()

GÊNERO
Male      878
Female    827
Name: count, dtype: int64

In [20]:
df["GÊNERO"] = df["GÊNERO"].replace({
    'Male': 'Masculino',
    'Female': 'Feminino'
})

df["GÊNERO"]

0       Masculino
1        Feminino
2       Masculino
3       Masculino
4        Feminino
          ...
1700     Feminino
1701    Masculino
1702     Feminino
1703    Masculino
1704     Feminino
Name: GÊNERO, Length: 1705, dtype: str

In [24]:
df["NÍVEL_ACADÊMICO"].unique()

<ArrowStringArray>
['Graduação', 'Pós-graduação', 'Ensino Médio']
Length: 3, dtype: str

In [23]:
df["NÍVEL_ACADÊMICO"] = df["NÍVEL_ACADÊMICO"].replace({
    'Undergraduate': 'Graduação',
    'Graduate': 'Pós-graduação',
    'High School': 'Ensino Médio'
})

In [25]:
df["PAÍS"].unique()

<ArrowStringArray>
[      'Other',      'Canada',         'USA',       'India',   'Australia',
          'UK',     'Germany',  'Bangladesh',      'Brazil',       'Japan',
 ...
     'Lebanon',        'Iraq',       'Yemen',       'Syria', 'Afghanistan',
    'Pakistan',       'Nepal',      'Bhutan',   'Sri Lanka',    'Maldives']
Length: 111, dtype: str

In [ ]:
from deep_translator import GoogleTranslator

# Traduzindo todos os registros da coluna "PAÍS"
df["PAÍS"] = df["PAÍS"].apply(lambda x: GoogleTranslator(source="en", target="pt").translate(x))

# Conferindo os primeiros resultados
print(df["PAÍS"].head())

In [31]:
df["PAÍS"].head()

0     Other
1     Other
2    Canada
3     Other
4     Other
Name: PAÍS, dtype: str